version: "3.8"

services:
  networth-api:
    build: .
    container_name: networth-tracker
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
